name: Ruby build xxx IR
on:
  workflow_dispatch:

jobs:
  RUBY:
    runs-on: ubuntu-latest
    name: Run build
    steps:

      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1' # specify your Ruby version
          
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # If you have a Gemfile
          gem list # This will list all installed gems
